name: MLflow CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow dagshub scikit-learn pandas numpy

      - name: Run mlflow project
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: mlflow run MLProject -P data_path=MLProject/landmine_preprocessing.csv --env-manager=local

      - name: Save latest run_id
        id: get-run
        run: |
          RUN_ID=$(ls -t mlruns/0 | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns/

  docker-build:
    runs-on: ubuntu-latest
    needs: build-train

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install MLflow
        run: pip install mlflow scikit-learn pandas numpy

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with MLflow
        run: mlflow models build-docker -m "mlruns/0/<RUN_ID>/artifacts/model" -n ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest
