name: MLflow CI/CD Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CSV_PATH: "landmine_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow project
        run: |
          mlflow run MLProject -P data_path=${{ env.CSV_PATH }} --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Commit MLflow artifacts
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add mlruns/
          git commit -m "Add MLflow run artifacts for run ${{ env.RUN_ID }}" || echo "No changes to commit"
          git push

      - name: Build Docker image from model
        run: |
          mlflow models build-docker -m "mlruns/0/${{ env.RUN_ID }}/artifacts/random_forest_model" -n "${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-model:latest"

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-model:latest
