name: MLflow CI/CD Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CSV_PATH: "landmine_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow project
        run: |
          export MLFLOW_TRACKING_URI=file:./mlruns
          mlflow run MLProject -P data_path=${{ env.CSV_PATH }} --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(mlflow runs list --experiment-id 0 | grep "RUNNING\|FINISHED" | head -n 1 | awk '{print $2}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Check if run_id exists
        run: |
          if [ -z "${{ env.RUN_ID }}" ]; then
            echo "Error: No valid run_id found"
            exit 1
          fi

      - name: Commit MLflow artifacts
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add mlruns/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add MLflow run artifacts for run ${{ env.RUN_ID }}"
            git push
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          mlflow models build-docker -m "mlruns/0/${{ env.RUN_ID }}/artifacts/random_forest_model" -n "${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-model:latest" --push
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
