name: MLflow CI/CD Workflow with GitHub Artifacts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CSV_URL: "MLProject/landmine_preprocessing.csv"
  TARGET_VAR: "Mine type"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.get_run_id.outputs.run_id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo $CSV_URL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run training script
        run: |
          mlflow run MLProject -P data_path=$CSV_URL --env-manager=local

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Commit MLflow artifacts to repo
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add mlruns/
          git commit -m "Add MLflow run artifacts for run ${{ env.RUN_ID }}" || echo "No changes to commit"
          git push

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/random_forest_model" --name "cc"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
