name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/landmine_preprocessing.csv"
  TARGET_VAR: "Mine type"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Check Env
      - name: Check Env
        run: |
          echo "CSV: $CSV_URL"
          echo "Target: $TARGET_VAR"

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas gdown

      # 5. Run as mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local

      # 6. Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # 7. Install Python dependencies (opsional tambahan sesuai log dosen)
      - name: Install Python dependencies
        run: |
          pip install requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python MLproject/upload_to_gdrive.py

      # 8. Upload artefak ke Google Drive
      - name: Upload to Google Drive
        run: |
          pip install --upgrade gdown
          zip -r model_artifact.zip mlruns
          gdown --id ${{ secrets.GDRIVE_FOLDER_ID }} --upload model_artifact.zip
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

      # 9. Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/random_forest_model" --name "mine-rf"

      # 10. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 11. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag mine-rf ${{ secrets.DOCKER_HUB_USERNAME }}/mine-rf:latest

      # 12. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mine-rf:latest
