name: MLflow CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install MLflow
        run: pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow Project
        run: mlflow run MLProject -P data_path=MLProject/landmine_preprocessing.csv

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: mlruns/

  docker-build:
    runs-on: ubuntu-latest
    needs: build-train
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with MLflow
        run: mlflow models build-docker -m "mlruns/0/<LATEST_RUN_ID>/artifacts/model" -n ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest
